# Generated by Django 5.2.6 on 2025-09-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shift_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
