# Generated by Django 5.2.6 on 2025-09-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_shift_date_shift_day_shift_month_shift_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swaprequest',
            old_name='requested_employee',
            new_name='requesting_employee',
        ),
        migrations.AlterUniqueTogether(
            name='swaprequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requested_employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
