# Generated by Django 5.2.6 on 2025-09-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_requested_employee_swaprequest_requesting_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='permissions',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User')], default=('Admin', 'Admin'), max_length=5, null=True),
        ),
    ]
