# Generated by Django 5.2.6 on 2025-10-08 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_shift_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaprequest',
            name='requesting_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
