# Generated by Django 5.2.6 on 2025-10-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_swaprequest_requesting_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
